# Generated by Django 4.0.6 on 2022-07-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
